### ISSUE TITLE
Player Shuttle Stats vs NPC Shuttle Stats

### ISSUE THREAD

**Issue by lastchaosmarine** [Squatnet/XwarsPublic#6]
![img_1489](https://user-images.githubusercontent.com/24637305/29751462-8448c504-8b45-11e7-967b-e4fe20ba653b.JPG)

Hopefully the image attaches and you can see what I mean . I think they just need to be changed so that player has the same stats as Npc.

**Comment by Squatnet** [comment]
Applies only to shuttle provided to new character. Shuttle bought from shipyard had correct values. Issue * fixed in 0.2.8
